// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Customer struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Register string `json:"register"`
}

type CustomerCreate struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Register string `json:"register"`
}

type CustomerUpdate struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Register *string `json:"register,omitempty"`
}

type Gym struct {
	ID        string    `json:"id"`
	Branch    string    `json:"branch"`
	Admin     string    `json:"admin"`
	Phone     string    `json:"phone"`
	Trainings *Training `json:"trainings"`
	Slots     int       `json:"slots"`
}

type GymCreate struct {
	Branch      string   `json:"branch"`
	Admin       string   `json:"admin"`
	Phone       string   `json:"phone"`
	TrainingIDs []string `json:"trainingIDs"`
	Slots       int      `json:"slots"`
}

type GymUpdate struct {
	Branch      *string   `json:"branch,omitempty"`
	Admin       *string   `json:"admin,omitempty"`
	Phone       *string   `json:"phone,omitempty"`
	TrainingIDs []*string `json:"trainingIDs,omitempty"`
	Slots       *int      `json:"slots,omitempty"`
}

type Purchase struct {
	ID       string    `json:"id"`
	Training *Training `json:"training"`
	Customer *Customer `json:"customer"`
	Coast    int       `json:"coast"`
	Income   int       `json:"income"`
}

type PurchaseCreate struct {
	Training string `json:"training"`
	Customer string `json:"customer"`
	Coast    int    `json:"coast"`
	Income   int    `json:"income"`
}

type PurchaseInput struct {
	Coast  *int `json:"coast,omitempty"`
	Income *int `json:"income,omitempty"`
}

type PurchaseUpdate struct {
	Training *string `json:"training,omitempty"`
	Customer *string `json:"customer,omitempty"`
	Coast    *int    `json:"coast,omitempty"`
	Income   *int    `json:"income,omitempty"`
}

type Training struct {
	ID       string `json:"id"`
	Category string `json:"category"`
	Coast    int    `json:"coast"`
	Gym      *Gym   `json:"gym"`
}

type TrainingCreate struct {
	Category string `json:"category"`
	Coast    int    `json:"coast"`
	GymID    string `json:"gymID"`
}

type TrainingUpdate struct {
	Category *string `json:"category,omitempty"`
	Coast    *int    `json:"coast,omitempty"`
	GymID    *string `json:"gymID,omitempty"`
}
