// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Customer struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Register []*Purchase `json:"register"`
}

type CustomerCreate struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type CustomerUpdate struct {
	ID    string  `json:"id"`
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type Gym struct {
	ID        string      `json:"id"`
	Branch    string      `json:"branch"`
	Admin     string      `json:"admin"`
	Phone     string      `json:"phone"`
	Trainings []*Training `json:"trainings"`
	Slots     int         `json:"slots"`
}

type GymCreate struct {
	Branch string `json:"branch"`
	Admin  string `json:"admin"`
	Phone  string `json:"phone"`
	Slots  int    `json:"slots"`
}

type GymUpdate struct {
	ID     string  `json:"id"`
	Branch *string `json:"branch,omitempty"`
	Admin  *string `json:"admin,omitempty"`
	Phone  *string `json:"phone,omitempty"`
	Slots  *int    `json:"slots,omitempty"`
}

type Purchase struct {
	ID       string    `json:"id"`
	Training *Training `json:"training"`
	Customer *Customer `json:"customer"`
	Coast    int       `json:"coast"`
	Income   float64   `json:"income"`
}

type Training struct {
	ID       string `json:"id"`
	Category string `json:"category"`
	Coast    int    `json:"coast"`
	Gym      *Gym   `json:"gym"`
}

type TrainingCreate struct {
	Category string `json:"category"`
	Coast    int    `json:"coast"`
	GymID    string `json:"gymID"`
}

type TrainingUpdate struct {
	ID       string  `json:"id"`
	Category *string `json:"category,omitempty"`
	Coast    *int    `json:"coast,omitempty"`
	GymID    *string `json:"gymID,omitempty"`
}
